"""remove growth_stage from parcels

Revision ID: 0890813f2d15
Revises: 35d59e9702d3
Create Date: 2026-08-14 15:13:42.562637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0890813f2d15'
down_revision: Union[str, None] = '35d59e9702d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcels', 'growth_stage')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('growth_stage', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###