"""initial schema

Revision ID: 6be214854654
Revises: 
Create Date: 2026-08-06 15:21:55.327302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be214854654'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('soil_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('efficiency_factors',
    sa.Column('soil_type_id', sa.UUID(), nullable=False),
    sa.Column('nutrient', sa.String(length=30), nullable=False),
    sa.Column('ef_min', sa.Float(), nullable=False),
    sa.Column('ef_max', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['soil_type_id'], ['soil_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_indices',
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('nutrient', sa.String(length=30), nullable=False),
    sa.Column('ie_value', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farms',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('area_hectares', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('varieties',
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incomes',
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('income_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcels',
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('variety_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('area_hectares', sa.Float(), nullable=False),
    sa.Column('planting_date', sa.Date(), nullable=False),
    sa.Column('growth_stage', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['varieties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variety_factors',
    sa.Column('variety_id', sa.UUID(), nullable=False),
    sa.Column('nutrient', sa.String(length=30), nullable=False),
    sa.Column('fv_factor', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['variety_id'], ['varieties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_analyses',
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('organic_matter_pct', sa.Float(), nullable=False),
    sa.Column('cic', sa.Float(), nullable=False),
    sa.Column('clay_pct', sa.Float(), nullable=False),
    sa.Column('silt_pct', sa.Float(), nullable=False),
    sa.Column('sand_pct', sa.Float(), nullable=False),
    sa.Column('nitrogen', sa.Float(), nullable=False),
    sa.Column('phosphorus', sa.Float(), nullable=False),
    sa.Column('potassium', sa.Float(), nullable=False),
    sa.Column('calcium', sa.Float(), nullable=False),
    sa.Column('magnesium', sa.Float(), nullable=False),
    sa.Column('sulfur', sa.Float(), nullable=False),
    sa.Column('lab', sa.String(length=150), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phenological_stages',
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('crop_id', sa.UUID(), nullable=True),
    sa.Column('parcel_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('estimated_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['phenological_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productions',
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('income_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['income_id'], ['incomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readings',
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('nitrogen', sa.Float(), nullable=False),
    sa.Column('phosphorus', sa.Float(), nullable=False),
    sa.Column('potassium', sa.Float(), nullable=False),
    sa.Column('ec', sa.Float(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fertilization_plans',
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('reading_id', sa.UUID(), nullable=True),
    sa.Column('lab_analysis_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('NOT (reading_id IS NOT NULL AND lab_analysis_id IS NOT NULL)', name='ck_fertilization_plan_single_source'),
    sa.ForeignKeyConstraint(['lab_analysis_id'], ['lab_analyses.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimal_requirements',
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('nutrient', sa.String(length=30), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['phenological_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_factors',
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('nutrient', sa.String(length=30), nullable=False),
    sa.Column('fe_factor', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['phenological_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_factors')
    op.drop_table('optimal_requirements')
    op.drop_table('fertilization_plans')
    op.drop_table('readings')
    op.drop_table('productions')
    op.drop_table('phenological_stages')
    op.drop_table('lab_analyses')
    op.drop_table('alerts')
    op.drop_table('variety_factors')
    op.drop_table('parcels')
    op.drop_table('incomes')
    op.drop_table('expenses')
    op.drop_table('varieties')
    op.drop_table('farms')
    op.drop_table('extraction_indices')
    op.drop_table('efficiency_factors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('soil_types')
    op.drop_table('crops')
    # ### end Alembic commands ###